name: Angular CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  install:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: —Åache deps
        uses: actions/cache@v2.1.3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: install
        run: yarn install --frozen-lockfile

      - name: lint
        run: yarn lint

      #- name: test
      #  run: yarn test --watch=false

      - name: build
        run: yarn build --prod
